---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lyrion-smb-credentials
  namespace: lyrion
spec:
  encryptedData:
    password: AgCCkjgWDiOmKlMC3Vfy8Ep9OFlrfHGRog6nu4k9021pUxvJPVu/e686w+J5co9ZX4P3mVHDaOyG1h/7RSP9VRJp6MUaS30vHIvKJUVw3fhI5PcwzJT46ciimLJ2iIyGrYIzFOefTOlxcuut3Fqz1rYJ12mvX1XaLtkojqZQeM0GALHfVi1bZpVcIxH30gBgOmGtb8ylpkLVwESuxwA4F3RCehd41dUk4op3rvUusSq54ALsfXxkxo2obIXP5Pguo1a5Hr4XMWmhe1L4tecidqb76bIRM8Ar57SiBA+Y7PR4DzAL6qK2c0pxTFS/Y1Yy59UxE/y+/hrBbMNd4BUQ802lMfPZBShfILNlOqjFqAqQARVoPROE8S12UKdPkTLsqPI17IZ3bTyRNJBCMIIzqzfHxBXyUtqgWDEdx+GU/T4Pnzy8up53nRvksL9L0nIG/MoNku4tud7pCs2d+/S+DuMQ/tLI0scyL3buLnYwSg7ETa8pFwUnpDEIoSL4/2UaB+eMmWr9JLP3ypw/nk7aabwjr6CuXzlR5Brn1psLHrnKkj3PtXmNfEzbodM3Kky7+aqsk+aQ1XZLrk+fR1z7dq1yUiP3L3WAENnMwy+3zdUrgE/zGO/JXcnht5cis1B6tZUjwQdoDVKJTqYq2idotK7HN5NjxJj911scC2GHU+slAcK0D8HF7AnJZ3mTUuoeiWQPKKxLcFw=
    username: AgAZCj90l73wbLEnE5Lw17w/ZKvIYExSyy1otUlLp88Axo2+AN4rJIUNUiZTSc+H0gmt0RsGE+2m467NZGTIB3LCHDIKyuLDrg6arHnyXV1nfjlsk/Yzq0n0eDxh93uMbw4u6dlNHp/ceo+b3va9rZMiNmfKe4sho3EVEvajp01BhCkYhv1bK6MxVRjMWo25Yjk4110uGL4QCW1W7U9Jdt/5uyEOuBF6yIKMrzQttVa039RnPBvMhPX4PQH3WQfxpuF2nh3dkQh9Pwh3jk7JVApo3+pD0fd9m7uinqKCmIRvMcqcKCqBVeODU3evanvt3QTOn5/7XwGbrcXsXmrONzORXyya8bIkmORhHQN3hzjIaEu7rhNeR69iw8J7ulZO6EqRuiSX9XfNpv3HmIiRPQ1oVdWnt9z+MDAtmNiLGEOCdDzJF+F0XBumcvQ/6e7+PWLk3ZfKRZsAOM5K8JeAdIElBGw9BDebQdlUp6EMf6LwEAV6/b/li4eSBRTtoNEHMRNag+lKHH5aHsKvBaFKM5TyVaUdV+bFhiHCMkFznXfctMO+ATvfnLNTfRf3fVgrZ8bnkiR6CbjyLsQIzWSPq1oQXJNGlTxdWNDPflbgK01o9/FiCLJjxqmO31T1CfnXPgCnZptaoaZrRP1tBsI4rGykTQzGnxiCVrXGBUmoD+wh/X4YJWgcPwUkQexvytbdCh8xdYZVHmg=
  template:
    metadata:
      name: lyrion-smb-credentials
      namespace: lyrion
