---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    INSTANCE_URL: AgA/fQQ5fhZfiaPq1w23HBXdtVWhKZIMJPkbtZRFP89BK7dlO037ExjLPfYPPINpoCCL5ZfgEpIO/JZh9uy88L/DMxarILlFQIHIH6Z3ZRQhrdmWOKoqXdNCMD6Ib9niA+lGIYNvgmMqAoW9VNdtgoa8gOzkQHbWJL5xKj/QfwcCMa6XvLXQGg7MNx2k11IAXPm8l6z8CqwzNo1PC0lnJ6zFBvlDWIy4SpaKkpPNBhvY5+kTMEPjISmftlsRuneBq1J1lee0T0Cf3zpyuvjai0hnLpJ0lyxfXKr+8bhisPj7mBKO0BUOPCIKy1pzXCGEG5PUUTyCTpVxUJkZe8dz5AqVV3+Gq7E06HF352ekVM2cw1icPDkoMl1I/pHAuainEtBrGd5wgd4P16iVEYDdI6j8QcQtjHpBYmxvoEI+KV9eUCb8OMhh2ku6TPVn9MBwaR9iQ+cw2AGs1bvqvd5h+cZcwxlFY/XE4Mc6C/bgviy1ftXxaRyiPsNcHTsHVtGg1I28R6hiv18is9eCXgJPCio9AqMN9HgbjYpDPY6fAcMis/GrtA9R1/PA4MoxV7YRAGVYKTY7X4bJwIcG7bVu/KExYQv4mCpLM4cqp1ZZK2bnBu17hUdxsqxkjdg48uZtUITRHwEG/BWUFqego06wFKleyPCveHE2EzDRGEKPjDbk2ZAgv20jXG0BdHxd7vLfLYgG/7l+A/x6KZfe+FgQ5rU48SCqKNk=
    RUNNER_SECRET: AgCihuZQBME5s2BK85l3xAtSWcjLkzhI4kJSWWrII7PZrdgGJqj/Ikmacm1+XTO0LAoE5E4B/DXhC6o+qmLEgEisVqyjkHJ2prS8g3kCTd/+lp4pYzfG/yXgJtjNf22W+79P4DsnjNx9kLiX5kO8w6rMVgUeLuTmwqqtO1U6dYOn5zEGWxLBfL7HV5nQx8IQF2qF1vbElT63rbdKzjiOvd+lYXn0m6RVf8+LV5Or1JT1uLVRVnti3miYoPXcLDlUz+1+dYxq97N/666rcy3Ekl37zhkqfuHv3UrS0cjl449UHm1fRFuD7AECg+lg7c2aaDCkExh0XdHaifx4c4n1xtrLeyN1LBGqZ4fEJ23BUtaTsvvgqr0YuFKLmTyEKMDSPDzsgcZLSpAaeAPkXAnhUqhtm3iq07i9DY1dF3xv+fXbu3PJf+n5ybRSnQ2wzslIWqTDfLAglyoaYXuIcEoEmNkz90ObXW+iYNBg334vrequJigbuBVlh3eNE5hX9bv9Vfq5rmVYV9+JkSP5tpeIPFdABB7ZOgDe3Aw1UaLtTJDUUZiEWi92UXk7m72HwbVYq3qyHNz4cnuvBAOTWdghLx66ah355Y5OlU1WH1rSUenZSWxIT8MOh62b7tjmEq7vCldWiikJqt6QuPBTR1qBB7MkMKsrOd8EgGDKK1Apj+OWZNCl2F86C+bFMPISsKHigRiLdOV+EoQTnOM6Goa2JJJ4wodfH9YPsPee1iWA8qVyb0w4oK+0EiJF
  template:
    metadata:
      name: forgejo-runner-secret
      namespace: forgejo
