---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    INSTANCE_URL: AgC+YwjqMvfb7BsHA8CsLZOsVYtk7QP26gGx9LuOlQKEj9GwbeZ8L8CCgT9ADEAHVomqD2yUScgWqvsmBWre43dioIdiuygOx8DEAZWX+YGYVo4P/mrPkyQDXKD1lZY0UP6Cs2uc3VM+EFvyLqPaltSAWZVmmvE1QRg9aYIjVVV/5UkFV5L++VRTnpGY53nJiOn2b4AKpjxjik/S/RqkyK6PXxZFf68vrWUCNI4iNZrw9KgxKRq0cJycAjhhMhwZavD5v/xYw6Nltz4+R+ESqYxWZx1l/c8You3HuzfHuE4CU4MMdf/VbsOe+DUB6MjoLIO3rK6Xp5hkFOMfgrx+fB9o1YuJNXUTzG/aIq65vbtT2eSddW48SdvFzLkuxVumrCRmdnXqbm2V8aoFrwxgd5qdpfIdrq54vLyDAFp0zbp4V8osjdDhk2zZvLjkrdCWEemWZhxYl0/XWH8o0KhkqOE3uR1lK3LzeSufSJMi0n1m486YlZu7G9gy4mSHFe8YV70hAO/8nswySczvQ3pHSRZWVydgOQ1ih7gTOV7sHB+BKzfTUkMJVu/zc9YGF/Qf/idREnWpqxbC2f/ZpD1lSKht2Tp3yxsDdwig90CdUdLGGe7//ZsinMLpT/Wh37RKL5XTuVwrHS1sGN3hu3cbnc/MRbi5q+E6S3r8JcK7iDFEAy4DlNZgRxpxMU4KLMsfI5WfuqBbZbN7ZE5XKmR5bCEpcoJvUNQ=
    RUNNER_SECRET: AgA61CeagNnygXxyJsoOfVjNceQYVBS2Eiqq4GepoN9PbAAAoWC946hQ9rOPr+wXNn3nIO4lucLi3cUn/U0RFciFo46t/yqMCoa1M5zXsqWnpom5yMkYruMXEF7svg0VrDuq5DU+8jQuR/y+eUd+C/DdQ2qiTiwyANADGC4dOOXx6PnhdFtPfwkxScJGzL2hjpxCf2GUh4QrXQzt+pNoWFl8SU5zaX4sZR2MaQkWI6Ui+0KhMQKSEbeCYxPeyZt79/N8948KpNYk1r9Njn97md4Czll0mMQKqdS4ow93S00jiBfwK92B83XiCin3We+OKRpHQ+gSjPi6Ttx7QgWL+TOdNijCLgLlZwCvMKOOeXzwsjz8igVZEAFJf9qQVwN0gjrX9XuXwVOlv2rG4AgCSzoEjZUeLA7KhlBZgmcl7JcvM1/o503PHQzqoE7dqVR7QIQ1NM6N0HPH/8cM4TkQrD+J/J5lB3Eb8Z+8cDBPzHHTYwgeUN27Sxbe1D0uHtW6AwH9YvcM1xcp3uGts9oBo624lSvDaP3yzdL56J6TFfJoatbSthhhzJyCF2NzTvBrDuwEMTTI0lnmgg/c+bu2A64MRqcUj3FPV8daalUJernFuaBc8TBflmton7MLZmHhnNN1gFUfp+15/ObhhxmF8is2ZutHytlFKH+xyYQxTH4wiLFBoiBBtNPGC5Vx8/z2Oo0tzx4OHbXx1oVtSpq/dVo5J50E8WU2IzbRCk1SXVgje+i5E9Qc8yiC
  template:
    metadata:
      name: forgejo-runner-secret
      namespace: forgejo
